<#
    .SYNOPSIS
    Regenerates the Rust crate section of THIRD-PARTY-NOTICES.md from the
    crates the release binaries actually link, or checks that it is current.

    .DESCRIPTION
    The section lists every crate in the normal (run-time) dependency closure
    of the engine (tigersetup-setup.exe, which every generated Setup.exe and
    every installed uninstaller carry) and the builder (tiger-setup.exe), for
    x86_64-pc-windows-msvc, as `cargo metadata` resolves it from Cargo.lock.
    Procedural macros and build-time dependencies run on the build machine
    only and are not part of any binary, so they are not listed; the
    workspace's own crates are TigerSetup's.

    For each crate the section records the licence selected (MIT where a crate
    offers MIT among its alternatives, which needs only the notice) and the
    copyright lines of its licence file, and it carries each distinct licence
    text once. The C loader links no Rust crate; zstd, the Fluent UI glyphs,
    the Rust standard library and SQLite have hand-written entries above the
    generated section.

    Run it after Cargo.lock changes. `-Check` rewrites nothing and fails when
    the committed section differs from what this script would write; the
    workspace test `third_party_notices` runs it.

    .EXAMPLE
    pwsh -File eng\Update-ThirdPartyNotices.ps1
    pwsh -File eng\Update-ThirdPartyNotices.ps1 -Check
#>
#Requires -Version 7.0
[CmdletBinding()]
param(
    # Report whether the committed section is current; write nothing.
    [switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$noticesPath = Join-Path $repoRoot 'THIRD-PARTY-NOTICES.md'
$begin = '<!-- rust-crates:begin (generated by eng/Update-ThirdPartyNotices.ps1; do not edit) -->'
$end = '<!-- rust-crates:end -->'
# The MIT permission notice, carried once beneath the copyright lines of every
# crate that uses it.
$mitText = @"
MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"@
$binaries = [ordered]@{ 'tigersetup-setup' = 'engine'; 'tigersetup-build' = 'builder' }

# --offline: the closure is what Cargo.lock already pins; nothing is fetched.
$json = & cargo metadata --format-version 1 --filter-platform x86_64-pc-windows-msvc --offline --manifest-path (Join-Path $repoRoot 'Cargo.toml') 2>$null
if ($LASTEXITCODE -ne 0) { throw "cargo metadata failed ($LASTEXITCODE)." }
$metadata = $json | ConvertFrom-Json -Depth 64

$packages = @{}
foreach ($package in $metadata.packages) { $packages[$package.id] = $package }
$nodes = @{}
foreach ($node in $metadata.resolve.nodes) { $nodes[$node.id] = $node }
$workspace = [Collections.Generic.HashSet[string]]::new([string[]] $metadata.workspace_members)

function Test-ProcMacro([object] $Package) {
    foreach ($target in $Package.targets) { if ($target.kind -contains 'proc-macro') { return $true } }
    return $false
}

# Normal edges only: a dev or build edge never reaches a shipped binary, and a
# procedural macro runs inside the compiler, so nothing below one ships either.
$usedBy = @{}
foreach ($binary in $binaries.Keys) {
    $root = @($metadata.packages | Where-Object { $_.name -ceq $binary -and $workspace.Contains($_.id) })[0]
    $seen = [Collections.Generic.HashSet[string]]::new()
    $queue = [Collections.Generic.Queue[string]]::new()
    $queue.Enqueue($root.id)
    while ($queue.Count) {
        $id = $queue.Dequeue()
        if (-not $seen.Add($id)) { continue }
        foreach ($dep in $nodes[$id].deps) {
            $normal = @($dep.dep_kinds | Where-Object { $null -eq $_.kind }).Count -gt 0
            if (-not $normal) { continue }
            if (Test-ProcMacro $packages[$dep.pkg]) { continue }
            $queue.Enqueue($dep.pkg)
        }
    }
    foreach ($id in $seen) {
        if ($workspace.Contains($id)) { continue }
        if (-not $usedBy.ContainsKey($id)) { $usedBy[$id] = [Collections.Generic.List[string]]::new() }
        $usedBy[$id].Add($binaries[$binary])
    }
}

function Get-SelectedLicense([string] $Expression) {
    $alternatives = @($Expression -split '\s+OR\s+|/' | ForEach-Object { $_.Trim('() ') })
    foreach ($preferred in 'MIT', 'Zlib', 'BSD-3-Clause', 'Apache-2.0') {
        if ($alternatives -contains $preferred) { return $preferred }
    }
    throw "No licence the notices know how to carry in '$Expression'."
}

function Get-LicenseFile([object] $Package, [string] $License) {
    $directory = Split-Path -Parent $Package.manifest_path
    $candidates = switch ($License) {
        'MIT' { 'LICENSE-MIT', 'LICENSE-MIT.md', 'LICENSE.MIT', 'LICENSE', 'LICENSE.md', 'LICENSE.txt', 'COPYING' }
        'Apache-2.0' { 'LICENSE-APACHE', 'LICENSE-APACHE.md', 'LICENSE', 'LICENSE.txt' }
        'Zlib' { 'LICENSE-ZLIB', 'LICENSE-ZLIB.md', 'LICENSE-Zlib', 'LICENSE', 'LICENSE.md', 'LICENSE.txt' }
        default { 'LICENSE', 'LICENSE.txt' }
    }
    foreach ($name in $candidates) {
        $path = Join-Path $directory $name
        if (Test-Path -LiteralPath $path -PathType Leaf) { return $path }
    }
    return $null
}

function Get-CopyrightLines([object] $Package, [string] $LicenseFile) {
    $lines = @()
    if ($LicenseFile) {
        $lines = @(Get-Content -LiteralPath $LicenseFile | ForEach-Object { $_.Trim() } |
            Where-Object { $_ -cmatch '^(Copyright\s+(\(c\)|\(C\)|©|\d{4})|\(c\)\s*\d|©)' -and $_ -notmatch '\[yyyy\]' })
    }
    if ($lines.Count -eq 0) {
        $authors = @($Package.authors | Where-Object { $_ })
        $holder = if ($authors.Count) { ($authors | ForEach-Object { $_ -replace '\s*<[^>]*>', '' }) -join ', ' } else { "the $($Package.name) authors" }
        $lines = @("Copyright (c) $holder")
    }
    return @($lines | Select-Object -Unique)
}

$crates = foreach ($id in $usedBy.Keys) {
    $package = $packages[$id]
    $license = Get-SelectedLicense $package.license
    $file = Get-LicenseFile $package $license
    [pscustomobject]@{
        name = $package.name
        version = $package.version
        expression = $package.license
        license = $license
        binaries = (@($usedBy[$id] | Sort-Object -Unique) -join ', ')
        copyright = Get-CopyrightLines $package $file
        file = $file
    }
}
$crates = @($crates | Sort-Object name, version)

$text = [Text.StringBuilder]::new()
$null = $text.AppendLine($begin)
$null = $text.AppendLine()
$null = $text.AppendLine('| Crate | Version | Licence (selected) | Linked into |')
$null = $text.AppendLine('|---|---|---|---|')
foreach ($crate in $crates) {
    $expression = $crate.expression -replace '/', ' OR '
    $selected = if ($expression -ceq $crate.license) { $crate.license } else { "$($crate.license) (of ``$expression``)" }
    $null = $text.AppendLine("| ``$($crate.name)`` | $($crate.version) | $selected | $($crate.binaries) |")
}
$null = $text.AppendLine()

foreach ($license in @($crates | ForEach-Object license | Sort-Object -Unique)) {
    $group = @($crates | Where-Object license -CEQ $license)
    $null = $text.AppendLine("### $license")
    $null = $text.AppendLine()
    if ($license -cin @('Zlib', 'BSD-3-Clause')) {
        # These licence texts name their own copyright holder, so each crate's
        # text is carried whole.
        foreach ($crate in $group) {
            $null = $text.AppendLine("``$($crate.name)`` $($crate.version):")
            $null = $text.AppendLine()
            $null = $text.AppendLine('```text')
            $null = $text.AppendLine(((Get-Content -LiteralPath $crate.file -Raw) -replace "`r`n", "`n").Trim())
            $null = $text.AppendLine('```')
            $null = $text.AppendLine()
        }
        continue
    }
    foreach ($crate in $group) {
        $null = $text.AppendLine("- ``$($crate.name)`` $($crate.version): $($crate.copyright -join '; ')")
    }
    $null = $text.AppendLine()
    $body = switch ($license) {
        'MIT' { $mitText }
        'Apache-2.0' { ((Get-Content -LiteralPath $group[0].file -Raw) -replace "`r`n", "`n").Trim() }
        default { throw "No licence text for $license." }
    }
    $null = $text.AppendLine('```text')
    $null = $text.AppendLine($body)
    $null = $text.AppendLine('```')
    $null = $text.AppendLine()
}
$null = $text.Append($end)
$section = $text.ToString() -replace "`r`n", "`n"

$current = (Get-Content -LiteralPath $noticesPath -Raw) -replace "`r`n", "`n"
$start = $current.IndexOf($begin)
$stop = $current.IndexOf($end)
if ($start -lt 0 -or $stop -lt $start) { throw "THIRD-PARTY-NOTICES.md has no generated section between '$begin' and '$end'." }
$updated = $current.Substring(0, $start) + $section + $current.Substring($stop + $end.Length)

if ($Check) {
    if ($updated -ceq $current) {
        Write-Host "PASS: THIRD-PARTY-NOTICES.md lists the $($crates.Count) crates the release binaries link."
        exit 0
    }
    Write-Host 'FAIL: THIRD-PARTY-NOTICES.md is not current; run pwsh -File eng\Update-ThirdPartyNotices.ps1.'
    exit 1
}
if ($updated -cne $current) {
    [IO.File]::WriteAllText($noticesPath, $updated, [Text.UTF8Encoding]::new($false))
    Write-Host "Updated THIRD-PARTY-NOTICES.md: $($crates.Count) crates."
}
else { Write-Host "THIRD-PARTY-NOTICES.md is current: $($crates.Count) crates." }